# Homework Week 3

In [1]:
import numpy as np

### Question 1

 - Store the below table into a numpy ndarray. Name it __table__.
 - Slice the shaded area in blue and store it in a variable __diagonal__.

![t_1](table_s.png)

In [2]:
table = np.arange(36).reshape((6,6))
diagonal = np.diag(table)

print(table)
print(diagonal)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 0  7 14 21 28 35]


### Question 2

Create an array of 2, 4, 6, 8, ..., 100.

In [3]:
even = np.arange(2,102,2)
print(even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Question 3


Create an 3D ndarray x with the dimensions  [10, 10, 3] with all elements set to zero. Reshape x so that the size of the second dimension equals 150.

In [4]:
array3d = np.zeros((10,10,3))
arrayReshaped = array3d.reshape((2,150,1))

### Question 4

Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [5]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])

## We can use the isin function to accomplish this task. 
boolArray = np.isin(x,y)

### Question 5

Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [6]:
myArray = np.arange(100,200,10).reshape((5,2))

### Question 6

Following is the input NumPy array delete column two and insert following new column in its place.

In [7]:

sampleArray = np.array([[94,43,53],[12,20,55],[50,101,3]]) 

newColumn = np.array([[101,101,101]])

sampleArray[:,1] = newColumn
print(sampleArray)

[[ 94 101  53]
 [ 12 101  55]
 [ 50 101   3]]


### Question 7


Given the below array print all the element that are bigger than 20

In [8]:
n_array = np.array([10,102,121,3,45,3,12,21])

print(n_array[np.where(n_array > 20)])

[102 121  45  21]


### Question 8

Sort the names of the below students based on their corresponding heights:

In [9]:
heights = np.random.randint(low=160, high=200, size=10)
Students = np.array(['Sami','Tony','Sarah','Huiyi','Samir','Osman','Avi','John','Yuki','Yanis'])

#Create a combined numpy array with students name and their heights
combined = np.array(list(zip(Students, heights)), dtype= [('name', 'S10'), ('height', float)])
#Use the sort function to sort by height
np.sort(combined, order='height')

array([(b'Sarah', 168.), (b'Sami', 172.), (b'Tony', 177.), (b'Avi', 179.),
       (b'John', 179.), (b'Osman', 184.), (b'Samir', 184.),
       (b'Yanis', 195.), (b'Huiyi', 198.), (b'Yuki', 198.)],
      dtype=[('name', 'S10'), ('height', '<f8')])

### Question 9

Using the seed number 10, create a random array of 100 elements and calculate its mean and standard deviation

In [10]:
np.random.seed(10)
xs = np.random.randn(100)

print("The mean is {}".format(np.mean(xs)))
print("The standard deviation is {}".format(np.std(xs)))

The mean is 0.07941666293687392
The standard deviation is 0.9670394771137057
