# Week 3: NumPy Basics

Numerical Python, also know as Numpy is one of the most important packages for computing and for Data scientists. The other packages that we will discuss later on this course are also based on it. It provides an effecient multi-dimentional array object, Mathmetical functions for fast operations on array data, linear algebra objects and methods.

## ndarray: A Multidimentional Array Object

ndarray is a fast, flexible container of large datasets in Python. Arrays enable you to perform numerical operations on large datasets using simple syntax, similar to the one you use to implement operations between to simple scalars.

In [1]:
import numpy as np

numpy is great for generating random series and storing them into arrays:

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[ 1.66983178, -1.43517625, -0.5514475 ],
       [-0.98331385,  0.71674781,  1.10655419]])

In [4]:
data*2

array([[ 3.33966356, -2.87035249, -1.102895  ],
       [-1.9666277 ,  1.43349563,  2.21310837]])

In [5]:
data + data

array([[ 3.33966356, -2.87035249, -1.102895  ],
       [-1.9666277 ,  1.43349563,  2.21310837]])

In [ ]:
Unlike the built-in Python sequences such as 